config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations', omniauth_callbacks: 'users/omniauth_callbacks' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  root to: 'application#welcome'

  resources :reviews
  resources :users do
    resources :shows
  end

  get '/custom_query', to: 'reviews#custom_query'
  get 'reviews/:id/next', to: 'reviews#next'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :show

  validates :rating, :numericality => { :less_than_or_equal_to => 5 }

  def self.five_stars
    all.where("rating = ?", 5)
  end

  def self.not_rated
    all.where("comment = ?", "Add a comment.") 
  end

  # def next
  #   review = Review.where("id > ?", id).first

  #   if review
  #     review
  #   else
  #     Review.first
  #   end
  # end

end

app/models/show.rb
class Show < ApplicationRecord
    has_many :reviews, :dependent => :destroy
    has_many :users, through: :reviews

    validates :title, :genre, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
          :recoverable, :rememberable, :validatable, :omniauthable

  has_many :reviews
  has_many :shows, through: :reviews
  validates :username, :email, :password, presence: true
  validates :username, uniqueness: true

  def self.from_omniauth(auth)
      # binding.pry
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.provider = auth.provider
      user.username = auth.info.nickname
      user.uid = auth.uid
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      end
  end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.gitgub_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
    
    def welcome
        get_data
        respond_to do |f|
            f.html {render :welcome}
            f.json {render json: @shows, each_serializer: ShowSerializer, root: 'application#welcome'}
        end
    end

    private

    def get_data
        @user = current_user
        @shows = Show.all
        @reviews = Review.all
    end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    before_action :authenticate_user!

private
    
    def sign_up_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :provider, :uid)
    end
    
    
    def account_update_params
        params.require(:user).permit(:username, :email, :password, :password_confirmation, :provider, :uid)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    before_action :authenticate_user!
    
  
    def index
        special_index
        find_review
        find_show
        respond_to do |f|
            f.html {render :index}
            f.json {render json: @reviews}
          end
    end

    def create
        @review = Review.create(user_id: current_user.id, shown_id: params[:show_id])
        if @review
            redirect_to reviews_path(@review)
        else
            render :show
        end
    end

    def edit
        find_review
        if current_user.reviews.include?(@review)
            render :edit
        else 
            redirect_to reviews_path
        end
    end

    def update
        find_review
        find_show
        @review.update(review_params)
        redirect_to user_show_path(@show)
    end

    #### Next button was removed
    # def next
    #     find_review
    #     find_show
    #     @next_review = @review.next
    #     render json: @next_review
    # end
    
    def show
        find_review
        find_show
        respond_to do |f|
          f.html {render :show}
          f.json {render json: @review}
        end
    end

    def custom_query
        special_index
    end 
        
private

    def review_params
        params.require(:review).permit(:rating, :comment)
    end

    def find_review
        @user = current_user
        @review = Review.find_by(id: params[:id])
    end

    def find_show
        @show = Show.find_by(id: params[:id])
    end

    def special_index
        @user = current_user
        @reviews = current_user.reviews
        five_stars = @reviews.five_stars
        not_rated = @reviews.not_rated
    end
end

app/controllers/shows_controller.rb
class ShowsController < ApplicationController
    before_action :authenticate_user!

    def index
        @shows = Show.all
        @user = current_user
        @reviews = current_user.reviews
    end

    def new
        @show = Show.new
        @user = current_user
    end

    def create
        @show = Show.new(show_params)
        find_user
        @user = (@user == current_user ? @user : current_user)
        @show.save    
        if @show.save
            @show.reviews.create(user_id: @user.id)
            render json: @show
        else
            render :new
        end
    end

    def show
        find_show
        @user = current_user
        @reviews = current_user.reviews
    end
    
    def edit
        find_show
        find_user
        if !@user.shows.include?(@show)
            redirect_to user_shows_path(current_user)
        end
    end

    def update
        find_show
        @show.update(show_params)
        find_user
        @user = (@user == current_user ? @user : current_user)
        if @show.save
            redirect_to user_show_path(@show)
        else
            render :edit
        end
    end

    def destroy
        @user = current_user
        find_show.destroy
        
        redirect_to user_shows_path 
    end

private
    
    def show_params
        params.require(:show).permit(:title, :genre)
    end

    def find_user
        @user = User.find_by(id: params[:user_id])
    end

    def find_show
        @show = Show.find_by(id: params[:id])
    end
    
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController

    def github
        # You need to implement the method below in your model (e.g. app/models/user.rb)
        @user = User.from_omniauth(request.env["omniauth.auth"])
    
        sign_in_and_redirect @user
      end
    
      def failure
        redirect_to root_path
      end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/welcome.html.erb
<%= render '/layouts/background' %>

<div>
    <h1>Welcome, <%= @user.username %>!</h1>

    <h3>Here are your reviews.</h3>
    <ul>
        <% @user.reviews.each do |review| %>
            <li>
                <b>Title:</b> <%= review.show.title %>
                <b> - Rating:</b> <%= review.rating %>
                <b> - Comment:</b> <%= review.comment %>
                <%= link_to "Edit This Review", 
                edit_review_path(review) %>
            </li>
            </br>
        <% end %>
    </ul>

    <h2>Shows Data Base</h2>

    <div id="ajax-index"></div>
</div>

app/views/layouts/_background.html.erb
<style>
  body {
  background: url(https://unsplash.com/photos/ngMtsE5r9eI) center no-repeat;
  background-size: cover;
  background-attachment: fixed;

</style>

app/views/layouts/_nav.html.erb
<nav>
  <div class="navbar navbar-default">
    <div class="container-fluid">
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Log Out", destroy_user_session_path, method: "delete" %></li>
          <li><%= link_to "Your Shows", user_shows_path(@user) %></li>
          <li><%= link_to "Add a New Show", new_user_show_path(@user) %></li>
          <li><%= link_to "Your Reviews", reviews_path %></li>
          <li><%= link_to "Five Star - Not Rated Shows", custom_query_path %>
        <% else %>
          <li><%= link_to "Sign up", new_user_registration_path %></li>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TVReviewApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
    <link rel="stylesheet" type="text/css" href="/style.css" media="screen" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Baloo+Bhai|Raleway&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div id='app-container'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/reviews/_form.html.erb
<% if @review.errors %>
  <%  @review.errors.full_messages.each do |error| %>
    <%= error %>
  <%end%>
<%end%>

<%= form_for(@review, method: :patch, html: {id: :review_form}) do |f| %> 
    <%= f.label :rating %>
    <%= f.number_field :rating, {max: 5} %><br />
    <%= f.label :comment %>
    <%= f.text_field :comment %><br />
    <br />
    <%= f.submit %>
<% end %>

app/views/reviews/custom_query.html.erb
<h1><%= current_user.username %>' 5-Star Reviews</h1>

<ol>
    <% @user.reviews.five_stars.each do |review| %>
        <li>
            <b>Title:</b> <%= review.show.title %>
            <b> - Rating:</b> <%= review.rating %>
            <b> - Comment:</b> <%= review.comment %>
            <%= link_to "Edit This Review", 
            edit_review_path(review) %>
        </li>
        </br>
    <% end %>
</ol>

</br>
<h1>These Shows Have Not Been Rated</h1>

<ol>
    <% @user.reviews.not_rated.each do |review| %>
        <li>
            <b>Title:</b> <%= review.show.title %>
            <b> - Rating:</b> <%= review.rating %>
            <b> - Comment:</b> <%= review.comment %>
            <%= link_to "Edit This Review", 
            edit_review_path(review) %>
        </li>
        </br>
    <% end %>
</ol>

app/views/reviews/edit.html.erb
<h1>Edit Review for <%= @review.show.title %></h1>
<%= render 'form' %>

app/views/reviews/index.html.erb
<h1><%= current_user.username %>'s Reviews Index</h1>

<div id="js-reviews-index"></div>

app/views/reviews/show.html.erb
<h1>Title: <%= @show.title %></h1>
<h3>Genre: <%= @show.genre %></h3> 
<h3>Rating: <%= @show.reviews.first.rating %></h3>
<h3>Comment: <%= @show.reviews.first.comment %></h3>

app/views/shows/_form.html.erb
<% if @show.errors %>
  <%  @show.errors.full_messages.each do |error| %>
    <%= error %>
  <%end%>
<%end%>

<%= form_for([user, show], html: {id: :new_show_form}) do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br />
    <%= f.label :genre %>
    <%= f.text_field :genre %><br />
    <br />
    <%= f.submit %>
<% end %>

app/views/shows/edit.html.erb
<h1>Edit <%= @show.title %></h1>
<% if @show.errors %>
  <%  @show.errors.full_messages.each do |error| %>
    <%= error %>
  <%end%>
<%end%>

<%= form_for [@user, @show] do |f| %>
    <%= f.label :title %>
    <%= f.text_field :title %><br />
    <%= f.label :genre %>
    <%= f.text_field :genre %><br />
    <br />
    <%= f.submit %>
<% end %>

app/views/shows/index.html.erb
<h1><%= @user.username %>'s Shows Index</h1>

<ol>
    <% @user.shows.each do |show| %>
    
        <li>
            <b>Title:</b><%= link_to show.title, user_show_path(@user, show) %> 
            <b>- Genre:</b> <%= show.genre %> 
            <b>- Rating:</b> <%= show.reviews.first.rating %> 
            <b>- Comment:</b> <%= show.reviews.first.comment %>
            <%= link_to "Edit This Show", edit_user_show_path(@user, show) %>
            <%= link_to 'Delete', user_show_path(@user, show), 
            method: :delete, data: { confirm: 'Are you sure?' } %>
        </li>
        </br>
    <% end %>
</ol>

app/views/shows/new.html.erb
<h1>Add A New Show</h1>

<%= render 'form', {:user => @user, :show => @show} %>

app/views/shows/show.html.erb
<h1>Title: <%= @show.title %></h1>
<h3>Genre: <%= @show.genre %></h3> 
<h3>Rating: <%= @show.reviews.first.rating %></h3>
<h3>Comment: <%= @show.reviews.first.comment %></h3>